### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'bhargav15'

### ISSUE THREAD

**Issue by bhargavravat** [akshaybahadur21/Facial-Recognition-using-Facenet#22] opened 2019-07-29 12:43 UTC
Using TensorFlow backend.
2019-07-29 18:07:21.830389: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/home/bhargav/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Total Params: 3743280
distance for bhargav15 is 0.07610167
bhargav15
Traceback (most recent call last):
 File "rec-feat.py", line 116, in <module>
    recognize()
  File "rec-feat.py", line 107, in recognize
    extract_face_info(img, img_rgb, database,ear)
  File "rec-feat.py", line 63, in extract_face_info
    name, min_dist = recognize_face(image, database)
  File "rec-feat.py", line 45, in recognize_face
    print(int(identity))
ValueError: invalid literal for int() with base 10: `'bhargav15'

**Comment by parasjain-12** [comment] 2019-11-15 17:41
You are facing this error because you have saved your images by name in "images" folder . Please save it by Id

**Comment by akshaybahadur21** [comment] 2021-07-02 20:01
Closing since the issue is resolved.

**Closed as completed by akshaybahadur21** 2021-07-02 20:01 UTC
